package dev.mcarr.a2fauthcompose.data.classes

/**
 * Abstract class from which any tokens should inherit,
 * regardless of whether it's HOTP, TOTP, Steam, or some
 * other type of token.
 *
 * @param password The token (password) generated by the
 * 2FA provider.
 * */
abstract class AbstractToken(
    val password: String
){

    companion object{
        const val TYPE_TOTP = "totp"
        const val TYPE_HOTP = "hotp"
    }

}