package dev.mcarr.a2fauthcompose.data.classes

/**
 * HOTP token provider.
 *
 * @param password The token (password) generated by the
 * 2FA provider.
 *
 * @see AbstractToken
 * */
class HotpToken(
    password: String
) : AbstractToken(
    password
) {

    /**
     * @param otp Generic OTP token from which
     * to derive the HOTP token/password.
     * */
    constructor(otp: OTP) : this(otp.password)

}